ImageItemType:
    type: object
    inherits:
        - BaseItemType
    config:
        interfaces:
            - ItemType
        fields:
            name:
                type: TextLineFieldDefinition
                resolve: '@=value.getFieldDefinition("name")'
            caption:
                type: MatrixFieldDefinition
                resolve: '@=value.getFieldDefinition("caption")'
            image:
                type: BinaryFieldDefinition
                resolve: '@=value.getFieldDefinition("image")'
