ItemGroupMediaTypes:
    type: object
    config:
        fields:
            file:
                type: FileItemType
                resolve: '@=resolver("ContentType", [{"identifier": "file"}])'
            image:
                type: ImageItemType
                resolve: '@=resolver("ContentType", [{"identifier": "image"}])'
