ProductCategoryTagItemConnection:
    type: relay-connection
    config:
        nodeType: ProductCategoryTagItem
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
