UserItemConnection:
    type: relay-connection
    config:
        nodeType: UserItem
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
